apiVersion: v1
kind: Secret
metadata:
  name: bloom-key
type: Opaque
stringData:
  bloom.key: |-
    eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJ1ZGR5YkB1cy5pYm0uY29tIiwiZXhwIjoxNjM5NTQ0NDAwLCJmZWF0dXJlVmVyc2lvbiI6IioiLCJvcmciOiJJQk0iLCJwdWIiOiJuZW80ai5jb20iLCJxdWFudGl0eSI6IjEwIiwicmVnIjoiQnVkZHkgQmFsbGVudGluZSIsInNjb3BlIjoiVHJpYWwiLCJzdWIiOiJuZW80ai1ibG9vbS1zZXJ2ZXIiLCJ2ZXIiOiIqIiwiaXNzIjoibmVvNGouY29tIiwibmJmIjoxNjE1OTE5NjI5LCJpYXQiOjE2MTU5MTk2MjksImp0aSI6InhYUlB2M1pYMyJ9.XYTXTHHm11SgnwLytrgEbI-YBnqIHXtDrCXz0ONO4Deb0Z0ifgwhNX6VDIEXA38YBKKVQcr4IEPX_FyIXXQ6IC5pgPxMzj1q_J9WLgrI6JI-sXKacGBNe0fSH0r7YdtyZhizr_mdYjO7pDSBjHFUkAnNx4U0Q9jHMfxyOsIyjxIBi1R_InVKG3pdOhR9mC7aaHiWdwwtxxhmb18De97j6-CFuafdax4nkURlxralpBuIAkwPShv-tRYTWdXtFVR-GJXsLKOzqQiukk9Yf7ka3CrO8KiVsgCOdvevpqTUekwqwbMcVdhHknTcybqJzU0i7wDtkHDx45Ed9no_5EcHfg
